# Generated by Django 5.0.6 on 2024-05-23 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='available_time',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='doctor.availabletime'),
        ),
    ]
